# Use root/example as user/password credentials
version: '3.1'

services:
  mariadb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clickartdb
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      -  "./baseDeDatos/:/var/lib/mysql:rw"
