Get http://localhost:3000/user
###

POST http://localhost:3000/resgistrarse

Content-Type: application/json

{
  "usuario":"Javier",
  "contrasena":"123456",
  "email":"jadepalermo@hotmail.com",
  "Kind_of_user":"1"
}

###
POST  http://localhost:3000/user
Content-Type: application/json

{
  "name":"Juan",
  "password":"123456"
}

###
POST  http://localhost:3000/user/login
Content-Type: application/json

{
  "name":"Juan",
  "password":"12456"
}